-- SUPERMARKET DATABASE

CREATE TABLE TIPO_DOCUMENTO(
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR (40) NOT NULL,
ACRONIMO VARCHAR (10) NOT NULL
);

CREATE TABLE CLIENTE (
ID INT IDENTITY(1,1) PRIMARY KEY,
NUMERO_DOCUMENTO VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
TELEFONO VARCHAR(40),
EMAIL VARCHAR(40),
DIRECCION VARCHAR(40),
ID_TIPO_DOCUMENTO INT FOREIGN KEY REFERENCES TIPO_DOCUMENTO (ID),
);

CREATE TABLE FACTURA (
ID INT IDENTITY(1,1) PRIMARY KEY,
NUMERO VARCHAR(40) NOT NULL,
VALOR_TOTAL DECIMAL NOT NULL,
VALOR_SUBTOTAL DECIMAL NOT NULL,
VALOR_IVA DECIMAL NOT NULL,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID)
);

CREATE TABLE PRODUCTO (
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(40) NOT NULL,
CANTIDAD INT,
VALOR_UNITARIO INT,
VALOR_TOTAL INT,
ID_FACTURA INT FOREIGN KEY REFERENCES FACTURA (ID)
);

CREATE TABLE INVENTARIO(
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO (ID),
TOTAL_UNIDADES INT,
TOTAL_MINIMO_UNIDADES INT,
TOTAL_MAXIMO_UNIDADES INT
);